// auto-generated by export_data.py — 2026-05-05
window.REPORT_DATA = {
  "meta": {
    "period": "2026 Q1",
    "dateRange": "1월 1일 ~ 5월 3일",
    "startDate": "2026-01-01",
    "endDate": "2026-05-03",
    "generatedAt": "2026-05-05 17:07",
    "curYear": 2026,
    "prevYear": 2025,
    "sources": {
      "cur": "고급모드->분석 데이터(2026)/콘텐츠 2026-01-01_2026-05-04 Giants TV",
      "prev": "과거 데이터/콘텐츠 2025-01-01_2025-05-06 Giants TV",
      "traffic": "고급모드->트래픽소스(2026)/트래픽 소스 2026-01-01_2026-05-04 Giants TV"
    }
  },
  "subscribers": {
    "lotte": {
      "name": "롯데",
      "subs": 376000,
      "delta": 2000
    },
    "teams": [
      {
        "name": "한화",
        "subs": 547000,
        "delta": 3000
      },
      {
        "name": "기아",
        "subs": 386000,
        "delta": 5000
      },
      {
        "name": "롯데",
        "subs": 376000,
        "delta": 2000
      },
      {
        "name": "삼성",
        "subs": 374000,
        "delta": 3000
      },
      {
        "name": "lg",
        "subs": 322000,
        "delta": 2000
      },
      {
        "name": "두산",
        "subs": 278000,
        "delta": 3000
      },
      {
        "name": "ssg",
        "subs": 221000,
        "delta": 2000
      },
      {
        "name": "NC",
        "subs": 129000,
        "delta": 1000
      },
      {
        "name": "kt",
        "subs": 123000,
        "delta": 1000
      },
      {
        "name": "키움",
        "subs": 122000,
        "delta": 0
      }
    ]
  },
  "counts": {
    "planned": {
      "cur": 93,
      "prev": 110
    },
    "fixed": {
      "cur": 139,
      "prev": 50
    },
    "semi": {
      "cur": 0,
      "prev": 2
    },
    "total": {
      "cur": 232,
      "prev": 162
    }
  },
  "planned": {
    "count": 93,
    "countPrev": 110,
    "avgViews": 102687,
    "avgViewsPrev": 115867,
    "totalViews": 9549851,
    "totalViewsPrev": 12745398,
    "watchTimeH": 697291,
    "watchTimeHPrev": 1032918,
    "avgDurFmt": "3분 14초",
    "avgDurFmtPrev": "2분 50초",
    "avgCTR": 7.07,
    "avgCTRPrev": 6.49,
    "totalSubs": 3835,
    "totalSubsPrev": 13161,
    "subConv": 40.2,
    "subConvPrev": 103.3,
    "newViewers": 0,
    "newViewersPrev": 0,
    "reVisitors": 0,
    "reVisitorsPrev": 0,
    "newViewersPct": 0.0,
    "newViewersPctPrev": 0.0
  },
  "fixed": {
    "count": 139,
    "countPrev": 50,
    "avgViews": 63658,
    "watchTimeH": 416368
  },
  "hotdug": {
    "cur": {
      "label": "HOTDUG",
      "count": 11,
      "avgViews": 98435,
      "watchTimeH": 117046,
      "subs": 612,
      "avgCTR": 8.1,
      "avgViewRate": 51.3
    },
    "prev": {
      "label": "#플레이볼",
      "count": 7,
      "avgViews": 93824,
      "watchTimeH": 65547,
      "subs": 663,
      "avgCTR": 10.51,
      "avgViewRate": 44.6
    }
  },
  "top10": [
    {
      "title": "DAY6 성진이 부르는 오늘도 승리한다🔥#DAY6 #성진 #롯데자이언츠 #응원가",
      "views": 428487,
      "ctr": 6.4,
      "tag": "콜라보"
    },
    {
      "title": "[미야자키 연습경기 생중계] vs 세이부라이온즈(2/22)",
      "views": 370854,
      "ctr": 15.8,
      "tag": "생중계"
    },
    {
      "title": "DAY6 성진이 부르는 영광의 순간🔥",
      "views": 304156,
      "ctr": 6.3,
      "tag": "콜라보"
    },
    {
      "title": "[미야자키 구춘리그] vs 지바롯데마린스 (3/1)",
      "views": 292365,
      "ctr": 14.3,
      "tag": "생중계"
    },
    {
      "title": "[미야자키 연습경기] vs SSG (3/3)",
      "views": 245716,
      "ctr": 15.0,
      "tag": "생중계"
    },
    {
      "title": "[미야자키 연습경기 생중계] vs 요미우리자이언츠(2/23)",
      "views": 236585,
      "ctr": 16.0,
      "tag": "생중계"
    },
    {
      "title": "[주간 예열🔥] 예열을 위한 미리 듣는 롯데자이언츠 응원가 시리즈 | 영광의 순간 feat. 데이식스 성진",
      "views": 233363,
      "ctr": 6.8,
      "tag": "콜라보"
    },
    {
      "title": "[미야자키 구춘리그] vs 두산베어스(2/26)",
      "views": 227961,
      "ctr": 16.0,
      "tag": "생중계"
    },
    {
      "title": "[Playlist] 2026 롯데자이언츠 팀 응원가 + 신규 응원가 포함! #직관전필수시청",
      "views": 215081,
      "ctr": 7.7,
      "tag": "기획"
    },
    {
      "title": "[미야자키 구춘리그] 빗속을 가르는 두 개의 홈런포🔥 #김민성 #레이예스",
      "views": 214549,
      "ctr": 8.5,
      "tag": "생중계"
    }
  ],
  "traffic": {
    "cur": {
      "label": "2026 1~5월",
      "data": [
        {
          "source": "탐색 기능",
          "views": 7857924,
          "ctr": 8.56,
          "pct": 42.5
        },
        {
          "source": "Shorts 피드",
          "views": 4985765,
          "ctr": 0.0,
          "pct": 27.0
        },
        {
          "source": "채널 페이지",
          "views": 1534474,
          "ctr": 5.68,
          "pct": 8.3
        },
        {
          "source": "추천 동영상",
          "views": 1497500,
          "ctr": 4.61,
          "pct": 8.1
        },
        {
          "source": "YouTube 검색",
          "views": 1318531,
          "ctr": 8.31,
          "pct": 7.1
        },
        {
          "source": "알림",
          "views": 358222,
          "ctr": 0.0,
          "pct": 1.9
        },
        {
          "source": "외부",
          "views": 246091,
          "ctr": 0.0,
          "pct": 1.3
        },
        {
          "source": "직접 입력 또는 알 수 없음",
          "views": 231633,
          "ctr": 0.0,
          "pct": 1.3
        },
        {
          "source": "기타 YouTube 기능",
          "views": 207342,
          "ctr": 0.0,
          "pct": 1.1
        },
        {
          "source": "재생목록",
          "views": 146633,
          "ctr": 6.0,
          "pct": 0.8
        },
        {
          "source": "최종 화면",
          "views": 76638,
          "ctr": 0.0,
          "pct": 0.4
        },
        {
          "source": "관련 Shorts 동영상",
          "views": 8642,
          "ctr": 0.0,
          "pct": 0.0
        },
        {
          "source": "세로형 실시간 피드",
          "views": 1424,
          "ctr": 0.0,
          "pct": 0.0
        },
        {
          "source": "해시태그 페이지",
          "views": 1087,
          "ctr": 0.0,
          "pct": 0.0
        },
        {
          "source": "사운드 페이지",
          "views": 423,
          "ctr": 0.0,
          "pct": 0.0
        },
        {
          "source": "리믹스 동영상",
          "views": 1,
          "ctr": 0.0,
          "pct": 0.0
        }
      ]
    },
    "prev": {
      "label": "2025 1~5월",
      "data": [
        {
          "source": "탐색 기능",
          "views": 7571831,
          "ctr": 8.18,
          "pct": 45.3
        },
        {
          "source": "Shorts 피드",
          "views": 3185179,
          "ctr": 0.0,
          "pct": 19.1
        },
        {
          "source": "채널 페이지",
          "views": 1787714,
          "ctr": 5.4,
          "pct": 10.7
        },
        {
          "source": "YouTube 검색",
          "views": 1576196,
          "ctr": 9.65,
          "pct": 9.4
        },
        {
          "source": "추천 동영상",
          "views": 1378887,
          "ctr": 3.78,
          "pct": 8.3
        },
        {
          "source": "알림",
          "views": 311106,
          "ctr": 0.0,
          "pct": 1.9
        },
        {
          "source": "기타 YouTube 기능",
          "views": 246423,
          "ctr": 0.0,
          "pct": 1.5
        },
        {
          "source": "외부",
          "views": 229135,
          "ctr": 0.0,
          "pct": 1.4
        },
        {
          "source": "직접 입력 또는 알 수 없음",
          "views": 218638,
          "ctr": 0.0,
          "pct": 1.3
        },
        {
          "source": "최종 화면",
          "views": 139532,
          "ctr": 0.0,
          "pct": 0.8
        },
        {
          "source": "재생목록",
          "views": 28651,
          "ctr": 7.28,
          "pct": 0.2
        },
        {
          "source": "관련 Shorts 동영상",
          "views": 18016,
          "ctr": 0.0,
          "pct": 0.1
        },
        {
          "source": "세로형 실시간 피드",
          "views": 7294,
          "ctr": 0.0,
          "pct": 0.0
        },
        {
          "source": "해시태그 페이지",
          "views": 1923,
          "ctr": 0.0,
          "pct": 0.0
        },
        {
          "source": "사운드 페이지",
          "views": 292,
          "ctr": 0.0,
          "pct": 0.0
        },
        {
          "source": "리믹스 동영상",
          "views": 7,
          "ctr": 0.0,
          "pct": 0.0
        }
      ]
    }
  },
  "daily": {
    "ctr": [],
    "likes": [
      {
        "date": "2026-01-01",
        "likes": 0
      },
      {
        "date": "2026-01-02",
        "likes": 0
      },
      {
        "date": "2026-01-03",
        "likes": 0
      },
      {
        "date": "2026-01-04",
        "likes": 0
      },
      {
        "date": "2026-01-05",
        "likes": 0
      },
      {
        "date": "2026-01-06",
        "likes": 0
      },
      {
        "date": "2026-01-07",
        "likes": 0
      },
      {
        "date": "2026-01-08",
        "likes": 2433
      },
      {
        "date": "2026-01-09",
        "likes": 215
      },
      {
        "date": "2026-01-10",
        "likes": 84
      },
      {
        "date": "2026-01-11",
        "likes": 33
      },
      {
        "date": "2026-01-12",
        "likes": 16
      },
      {
        "date": "2026-01-13",
        "likes": 21
      },
      {
        "date": "2026-01-14",
        "likes": 12
      },
      {
        "date": "2026-01-15",
        "likes": 9
      },
      {
        "date": "2026-01-16",
        "likes": 6
      },
      {
        "date": "2026-01-17",
        "likes": 3
      },
      {
        "date": "2026-01-18",
        "likes": 2
      },
      {
        "date": "2026-01-19",
        "likes": 10
      },
      {
        "date": "2026-01-20",
        "likes": 6
      },
      {
        "date": "2026-01-21",
        "likes": 2
      },
      {
        "date": "2026-01-22",
        "likes": 5
      },
      {
        "date": "2026-01-23",
        "likes": 1
      },
      {
        "date": "2026-01-24",
        "likes": 2
      },
      {
        "date": "2026-01-25",
        "likes": 3
      },
      {
        "date": "2026-01-26",
        "likes": 2027
      },
      {
        "date": "2026-01-27",
        "likes": 1107
      },
      {
        "date": "2026-01-28",
        "likes": 2201
      },
      {
        "date": "2026-01-29",
        "likes": 2679
      },
      {
        "date": "2026-01-30",
        "likes": 2671
      },
      {
        "date": "2026-01-31",
        "likes": 2266
      },
      {
        "date": "2026-02-01",
        "likes": 2591
      },
      {
        "date": "2026-02-02",
        "likes": 2771
      },
      {
        "date": "2026-02-03",
        "likes": 3383
      },
      {
        "date": "2026-02-04",
        "likes": 2545
      },
      {
        "date": "2026-02-05",
        "likes": 2561
      },
      {
        "date": "2026-02-06",
        "likes": 2675
      },
      {
        "date": "2026-02-07",
        "likes": 2335
      },
      {
        "date": "2026-02-08",
        "likes": 2987
      },
      {
        "date": "2026-02-09",
        "likes": 2246
      },
      {
        "date": "2026-02-10",
        "likes": 2447
      },
      {
        "date": "2026-02-11",
        "likes": 846
      },
      {
        "date": "2026-02-12",
        "likes": 2188
      },
      {
        "date": "2026-02-13",
        "likes": 192
      },
      {
        "date": "2026-02-14",
        "likes": 117
      },
      {
        "date": "2026-02-15",
        "likes": 62
      },
      {
        "date": "2026-02-16",
        "likes": 47
      },
      {
        "date": "2026-02-17",
        "likes": 56
      },
      {
        "date": "2026-02-18",
        "likes": 32
      },
      {
        "date": "2026-02-19",
        "likes": 28
      },
      {
        "date": "2026-02-20",
        "likes": 24
      },
      {
        "date": "2026-02-21",
        "likes": 4239
      },
      {
        "date": "2026-02-22",
        "likes": 5084
      },
      {
        "date": "2026-02-23",
        "likes": 1727
      },
      {
        "date": "2026-02-24",
        "likes": 1054
      },
      {
        "date": "2026-02-25",
        "likes": 4202
      },
      {
        "date": "2026-02-26",
        "likes": 3423
      },
      {
        "date": "2026-02-27",
        "likes": 604
      },
      {
        "date": "2026-02-28",
        "likes": 3554
      },
      {
        "date": "2026-03-01",
        "likes": 2966
      },
      {
        "date": "2026-03-02",
        "likes": 2968
      },
      {
        "date": "2026-03-03",
        "likes": 1430
      },
      {
        "date": "2026-03-04",
        "likes": 690
      },
      {
        "date": "2026-03-05",
        "likes": 98
      },
      {
        "date": "2026-03-06",
        "likes": 72
      },
      {
        "date": "2026-03-07",
        "likes": 47
      },
      {
        "date": "2026-03-08",
        "likes": 1598
      },
      {
        "date": "2026-03-09",
        "likes": 1299
      },
      {
        "date": "2026-03-10",
        "likes": 2423
      },
      {
        "date": "2026-03-11",
        "likes": 2910
      },
      {
        "date": "2026-03-12",
        "likes": 8144
      },
      {
        "date": "2026-03-13",
        "likes": 12911
      },
      {
        "date": "2026-03-14",
        "likes": 18450
      },
      {
        "date": "2026-03-15",
        "likes": 12384
      },
      {
        "date": "2026-03-16",
        "likes": 7473
      },
      {
        "date": "2026-03-17",
        "likes": 1639
      },
      {
        "date": "2026-03-18",
        "likes": 3055
      },
      {
        "date": "2026-03-19",
        "likes": 4926
      },
      {
        "date": "2026-03-20",
        "likes": 1104
      },
      {
        "date": "2026-03-21",
        "likes": 2869
      },
      {
        "date": "2026-03-22",
        "likes": 5520
      },
      {
        "date": "2026-03-23",
        "likes": 6917
      },
      {
        "date": "2026-03-24",
        "likes": 5756
      },
      {
        "date": "2026-03-25",
        "likes": 3123
      },
      {
        "date": "2026-03-26",
        "likes": 3293
      },
      {
        "date": "2026-03-27",
        "likes": 4294
      },
      {
        "date": "2026-03-28",
        "likes": 27656
      },
      {
        "date": "2026-03-29",
        "likes": 18351
      },
      {
        "date": "2026-03-30",
        "likes": 3865
      },
      {
        "date": "2026-03-31",
        "likes": 999
      },
      {
        "date": "2026-04-01",
        "likes": 679
      },
      {
        "date": "2026-04-02",
        "likes": 495
      },
      {
        "date": "2026-04-03",
        "likes": 693
      },
      {
        "date": "2026-04-04",
        "likes": 306
      },
      {
        "date": "2026-04-05",
        "likes": 78
      },
      {
        "date": "2026-04-06",
        "likes": 114
      },
      {
        "date": "2026-04-07",
        "likes": 95
      },
      {
        "date": "2026-04-08",
        "likes": 18005
      },
      {
        "date": "2026-04-09",
        "likes": 4795
      },
      {
        "date": "2026-04-10",
        "likes": 20119
      },
      {
        "date": "2026-04-11",
        "likes": 17127
      },
      {
        "date": "2026-04-12",
        "likes": 1199
      },
      {
        "date": "2026-04-13",
        "likes": 396
      },
      {
        "date": "2026-04-14",
        "likes": 271
      },
      {
        "date": "2026-04-15",
        "likes": 16596
      },
      {
        "date": "2026-04-16",
        "likes": 1372
      },
      {
        "date": "2026-04-17",
        "likes": 4236
      },
      {
        "date": "2026-04-18",
        "likes": 1918
      },
      {
        "date": "2026-04-19",
        "likes": 463
      },
      {
        "date": "2026-04-20",
        "likes": 0
      },
      {
        "date": "2026-04-21",
        "likes": 0
      },
      {
        "date": "2026-04-22",
        "likes": 0
      },
      {
        "date": "2026-04-23",
        "likes": 0
      },
      {
        "date": "2026-04-24",
        "likes": 2657
      },
      {
        "date": "2026-04-25",
        "likes": 729
      },
      {
        "date": "2026-04-26",
        "likes": 1607
      }
    ]
  }
};
